### ISSUE TITLE
NEED HELP

### ISSUE THREAD

**Issue by soltani123-Bilel** [taneishi/dlvs#1]
when i tried to compile your project i experienced an error which is as follows :
File "C:\Users\SOLTANI BILEL\Desktop\dlvs-master\main.py", line 89, in main
    train_dataloader, test_dataloader = load_dataset(args, device)
  File "C:\Users\SOLTANI BILEL\Desktop\dlvs-master\main.py", line 30, in load_dataset
    data = np.load(aargs.datafile)
  File "C:\Users\SOLTANI BILEL\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/cpi_preprocessed.npz'

**Comment by taneishi** [comment]
Hi, please run `python preprocess.py` before running main.py.
I updated README adding this step. Thank you.

**Comment by soltani123-Bilel** [comment]
when i tried to compile your project i experienced an error which is as follows :
"C:\Users\SOLTANI BILEL\AppData\Local\Programs\Python\Python39\python.exe" "C:/Users/SOLTANI BILEL/Desktop/dlvs-master/preprocess.py"
Traceback (most recent call last):
  File "C:\Users\SOLTANI BILEL\Desktop\dlvs-master\preprocess.py", line 32, in <module>
    main(args)
  File "C:\Users\SOLTANI BILEL\Desktop\dlvs-master\preprocess.py", line 10, in main
    data = np.load(Args.datafile)['data']
  File "C:\Users\SOLTANI BILEL\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\lib\npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/cpi.npz'

Process finished with exit code 1

**Comment by taneishi** [comment]
This error caused by relative path 'data/cpi.npz' could not solved.
I rewrote preprocess.py and main.py with absolute paths. Please checkout the latest master and re-run.

**Comment by Soltani-Bilel** [comment]
I have thr same problm when i tried to compile the priject please help me

**Comment by soltani123-Bilel** [comment]
PLEASE  send me data file  
my email : soltanibilel43@gmail.com 
thank you

**Comment by taneishi** [comment]
I commited an example `data/cpi.npz` file. Please pull the latest master branch.

**Comment by soltani123-Bilel** [comment]
what is the version of python who uesed it
and  how can i dowload the requirment send link 
thank u

**Comment by taneishi** [comment]
You can download the example file from `https://github.com/taneishi/dlvs/blob/master/data/cpi.npz`.

**Comment by soltani123-Bilel** [comment]
raceback (most recent call last):
  File "C:\Users\SOLTANI BILEL\Desktop\dlvs-master\main.py", line 2, in <module>
    import torch
  File "C:\Users\SOLTANI BILEL\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\__init__.py", line 196, in <module>
    from torch._C import *
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

**Comment by taneishi** [comment]
This error is caused by a mismatch of torch and numpy. Please try to reinstall torch and numpy at once from the dependency.

**Comment by soltani123-Bilel** [comment]
the result is in forme of graph

**Comment by taneishi** [comment]
OK, it's a feature request. This issue is closed.

**Comment by soltani123-Bilel** [comment]
how can i see the result !!!

**Comment by soltani123-Bilel** [comment]
i can't see the result

**Comment by Soltani-Bilel** [comment]
File.pth why can i open it

**Comment by soltani123-Bilel** [comment]
i canit open the model because the file is .PTH
